
/*Authentication*/
export const AUTHENTICATE = "AUTHENTICATE";
export const LOGOUT = "LOGOUT";
export const TRY_AUTHENTICATE = "TRY_AUTHENTICATE";

/*Getting information*/
export const FETCH_INFO = "FETCH_INFO";
export const ADD_INFO = "ADD_INFO";
export const FETCH_LOCATIONS = "FETCH_LOCATIONS";
export const ADD_LOCATIONS = "ADD_LOCATIONS";

/*Input*/
export const WRONG_INPUT = "WRONG_INPUT";
export const CORRECT_INPUT = "CORRECT_INPUT";
export const RESET_INPUT = "RESET_INPUT";

/*Appointments*/
export const MAKE_APPOINTMENT = "MAKE_APPOINTMENT";
export const TRY_MAKE_APPOINTMENT = "TRY_MAKE_APPOINTMENT";
export const GET_APPOINTMENTS = "GET_APPOINTMENTS";
export const ADD_APPOINTMENTS = "ADD_APPOINTMENTS";
export const DELETE_APPOINTMENTS = "DELETE_APPOINTMENTS";
export const CANCEL_APPOINTMENT = "CANCEL_APPOINTMENT";
export const TRY_CANCEL_APPOINTMENT = "TRY_CANCEL_APPOINTMENT";